### ISSUE TITLE
Reaviz Update Url

### ISSUE THREAD

**Issue by indifferentghost** [enaqx/awesome-react#1123]
[jask-oss/reaviz](https://github.com/jask-oss/reaviz) seems to have been moved to [reaviz/reaviz](https://github.com/reaviz/reaviz) and is causing a 404 in the build.

[Jask was acquired by Sumo Logic](https://www.sumologic.com/press-release/acquires-jask-to-expand-cloud-native-security-intelligence/)

**Comment by HTMLGhozt** [comment]
This was fixed in #1117.
