### ISSUE TITLE
Formatting Inconsistencies and Style Guide.

### ISSUE THREAD

**Issue by indifferentghost** [enaqx/awesome-react#1125]
There seems to be two different link formats, one where the resource title is a link and the description is not
> [example](example.com) - an example webpage

and one where both the title and description are included in a link
> [example - an example webpage](example.com)

I would recommend creating a style guide for consistency.

**Comment by KarenEfereyan** [comment]
@HTMLGhozt I would like to take this up? How should the style guide be formatted? Am i to use the first format where both resource title and description are links? In that case, will they be pointing to the same thing?

**Comment by devapurva** [comment]
@KarenEfereyan  I think what @HTMLGhozt  means is, it should be in a single format. Either the first one or the second one.

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan  I think what @HTMLGhozt  means is, it should be in a single format. Either the first one or the second one.  And follow it accordingly across the code.

Oh okay thanks so much.

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan  I think what @HTMLGhozt  means is, it should be in a single format. Either the first one or the second one.  And follow it accordingly across the code.

Oh okay thanks so much.
