### ISSUE TITLE
Wrong description for tailwind-react-ui

### ISSUE THREAD

**Issue by abhijit-hota** [enaqx/awesome-react#1136]
It seems like the description for tailwind-react-ui in the [React Component Libraries section](https://github.com/enaqx/awesome-react#react-component-libraries) is copied again from the previous one:

> - trunx - Super Saiyan React components, son of awesome Bulma, implemented in TypeScript
> - tailwind-react-ui - Super Saiyan React components, son of awesome Bulma, implemented in TypeScript

The description for tailwind-react-ui should be:
> React utility component primitives & UI framework for use with Tailwind CSS

as mentioned in their [GitHub repo](https://github.com/emortlock/tailwind-react-ui).

Can I submit a PR fixing this?

**Comment by Haroenv** [comment]
Thanks for noting this! I did not notice your question at the end though, you definitely can make a PR for these issues in the future!

**Comment by abhijit-hota** [comment]
> Thanks for noting this! I did not notice your question at the end though, you definitely can make a PR for these issues in the future!

No problem. Glad it's fixed! 👍
