### ISSUE TITLE
Proposal to include a section on React Websites

### ISSUE THREAD

**Issue by ademidun** [enaqx/awesome-react#1161]
Often when building a React website, users may prefer to take an existing React website or landing page template and build upon it.

It would be useful to have a collection of such open source react websites.

What I'm proposing might already be covered by the [Demo React Apps](https://github.com/enaqx/awesome-react#demo-react-apps) and [Real React Apps](https://github.com/enaqx/awesome-react#real-react-apps) section.

If that is the case, that's fine, please let me know what categories the following links belong into and if someone could make a PR to add them to the appropriate section that would be appreciated. Otherwise, I can also do it myself, I just need to know what categories each link belongs in.

- https://github.com/ant-design/ant-design-landing
- https://github.com/hackclub/site
- https://github.com/atilatech/government-fyi
- https://github.com/cjimmy/ballotfyi/ (that link is now broken but it was used to make this site: https://2018.ballot.fyi/)

Upon further thinking if infact most of these belong in Real React Apps, it feels like that section should have a lot more links. I'm basing this on my assumption that there are probably lots of high-quality open-sourced React websites that could be added to this project. 

Let me know what you folks think.

Great work to everyone who contributed to this by the way, I'm really glad that this repo exists. :smile:

**Comment by Haroenv** [comment]
I think real react apps fits the examples you're listing best, thanks!
