### ISSUE TITLE
Add razzle back to Development tools

### ISSUE THREAD

**Issue by zzeni** [enaqx/awesome-react#1205]
I've noticed that [a while ago](https://github.com/enaqx/awesome-react/pull/896/files) a reference to [razzle](https://razzlejs.org/) has been added to the list of development tools. But it seems that later it was removed (without a trace), because now it's missing.

Since it's still one of the few nice tools for bootstrapping SSR react apps, should we add it back?

**Comment by Haroenv** [comment]
Yes, it must have been an accident. Please make a pr, thx!

**Comment by zzeni** [comment]
Thanks @Haroenv 

Just created created one that also adds Neutrino and create-react-library :)
