### ISSUE TITLE
Website for the repo

### ISSUE THREAD

**Issue by fernandobelotto** [enaqx/awesome-react#1279]
Hi guys,

i created a docusaurus website based on the repo to facilitated the usage and i deploy to vercel. I found the repo quite useful and i would like to contribute linking the site in the repo. What you guys think? 

here is the link to checkout [link](https://react-awesome.vercel.app)

**Comment by SauveJeanLuc** [comment]
@fernandobelotto I Think I can raise this as a PR.
Mentioning it as a DEMO Live preview of the project's website until It's accepted and you link it.
