### ISSUE TITLE
OAuth2 libraries?

### ISSUE THREAD

**Issue by jestrickler** [enaqx/awesome-react#1300]
What about authentication/authorization libraries? This seems like something many developers would need to tackle, but I have trouble gauging the most popular solutions for this issue, and the information seems muddied by backend providers. I personally used AppAuth.js for our last project, just due to some familiarity with AppAuth-Android. Some other libraries that showed up in Google search and sparked some interest:

@react-keycloak/web (keycloak is our backend auth solution)
@auth0/auth0-react (seems popular, but is this based on backend popularity?)
react-auth-kit

**Comment by karesztrk** [comment]
Thats wonderful idea. Please add them. I have something similar called [useAuth](https://useauth.dev/)

**Comment by karesztrk** [comment]
@jestrickler FYI https://github.com/enaqx/awesome-react/pull/1302

**Comment by enaqx** [comment]
Auth0 and similar auth providers are not specific to React.
