### ISSUE TITLE
ReactGalaxy -> A website for this repository (and more) 💫

### ISSUE THREAD

**Issue by mutasim77** [enaqx/awesome-react#1383]
I've created a website with a good UI that includes information from this repository as well as from various other sources. It would be great if you could add the link to the repo's Link  

ReactGalaxy 💫 -> https://react-ecosystem-livid.vercel.app/

**Comment by reactslayer** [comment]
> I've created a website with a good UI that includes information from this repository as well as from various other sources. It would be great if you could add the link to the repo's Link
> 
> ReactGalaxy 💫 -> https://react-ecosystem-livid.vercel.app/

Nice! I would suggest you take a look at material design guidelines.

**Comment by mutasim77** [comment]
> > I've created a website with a good UI that includes information from this repository as well as from various other sources. It would be great if you could add the link to the repo's Link
> > ReactGalaxy 💫 -> https://react-ecosystem-livid.vercel.app/
> 
> Nice! I would suggest you take a look at material design guidelines.

I would be really happy if you could send me some resources, or any PRs are welcome to help improve the repo ;)

**Comment by enaqx** [comment]
Thanks
