### ISSUE TITLE
729 links! Time for organization

### ISSUE THREAD

**Issue by brigand** [enaqx/awesome-react#203]
The list is great but it has some structural problems that could be fixed.

### New React Users

You can't really link new people to this because there's no clear starting place. This could be solved with a curated 'must read' section with 15-25 links. Thinking in react, react-router, the flux primer, one of Pete Hunt's conference talks, etc. The really important stuff when getting into react.

### About X in format Y related to Z

This is where things get complicated and a "no" would be understandable. It needs a site where you can filter, which means a little bit of metadata needs to be added for each link. This also lets us add things like the angular/backbone/youtube/github badges on each item to make it easy to identify the X Y and Z in a potentially long list of items.

Metadata:
 - language (js, cljs, coffeescript, typescript, ...)
 - content type[] (tutorial, repo, video, component, blog, official, ...)
   - official+video (conference) vs tutorial+video
 - frameworks[] (angular, backbone, ...)
 - other?

I'm willing to put in the time for this part.

### Technical notes:

Probably yaml files, and autogenerating the readme and site from that.

**Comment by wmertens** [comment]
A beginner section would be great and a http://react.rocks mashup would
indeed be nice but a departure from the "awesome-x" meme.

On Thu, Jul 9, 2015, 09:46 Frankie Bagnardi <notifications@github.com>
wrote:

> The list is great but it has some structural problems that could be fixed.
> New React Users
>
> You can't really link new people to this because there's no clear starting
> place. This could be solved with a curated 'must read' section with 15-25
> links. Thinking in react, react-router, the flux primer, one of Pete Hunt's
> conference talks, etc. The really important stuff when getting into react.
> About X in format Y related to Z
>
> This is where things get complicated and a "no" would be understandable.
> It needs a site where you can filter, which means a little bit of metadata
> needs to be added for each link. This also lets us add things like the
> angular/backbone/youtube/github badges on each item to make it easy to
> identify the X Y and Z in a potentially long list of items.
>
> Metadata:
>
>    - language (js, cljs, coffeescript, typescript, ...)
>    - content type
>    <http://tutorial,%20repo,%20video,%20component,%20blog,%20official,%20...>
>       - official+video (conference) vs tutorial+video
>     - frameworks <http://angular,%20backbone,%20...>
>    - other?
>
> I'm willing to put in the time for this part.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enaqx/awesome-react/issues/203>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by enaqx** [comment]
@brigand. :+1: 
I've talked several times in community channels about extending functionality of this list. Most of the guys who concern about it think it's better to keep it in form of simple text list. Nonetheless if you will start some static generation from this list I can keep up. Sorry, kinda busy these weeks to start something like this on my own. 

If you want to contribute beginners guide  section, PR it. I'm ready for any kind of suggestion. Anyway, thanks for contribution.

P.S. I will repeat once more. I'm open to deletion PRs, not only addition. Despite that, most of the guys tend to use this list as promotion point. :)

**Comment by enaqx** [comment]
Ok, I think this problem is acknowledged. Anyone wishes to help, pls PR. You can PR suggestion for deletion or suggestions to "best of the best must read little list". I will do this also on my spare time.

**Comment by brigand** [comment]
Cool, I'll try to find time soon to start working on organizing these and making the site.
