### ISSUE TITLE
React/JSX + Typescript is a thing as of Typescript 1.6 btw

### ISSUE THREAD

**Issue by ichpuchtli** [enaqx/awesome-react#268]
# Announcement
http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx

> One of the key philosophies of TypeScript is to let you write TypeScript anywhere you can develop using JavaScript.  While we’ve worked with teams such as Dojo, Aurelia, and Angular to ensure using TypeScript is as easy as using JavaScript, there was still an important library that that presented a difficulty for TypeScript developers: React.  This was due to the lack of support for JSX, a popular way of writing DOM and native components in JS.  React heavily leverages JSX in everyday code.  Unfortunately, the syntax for JSX conflicted with the cast syntax that TypeScript already used.

![image](http://blogs.msdn.com/resized-image.ashx/__size/550x0/__key/communityserver-blogs-components-weblogfiles/00-00-01-56-67/6177.Renaming.gif)

> Refactoring JSX members in TypeScript (click to watch animation)

> In 1.6, we’ve introduced a new .tsx file extension.  This extension does two things: it enables JSX inside of TypeScript files, and it makes the new ‘as’ operator the default way to cast.  With this, we’ve added full support for working with React/JSX in TypeScript in a type-safe way.

# Details
https://github.com/Microsoft/TypeScript/wiki/JSX

**Comment by enaqx** [comment]
Thanks! Updated with b71fd61ddadf3ae3743a00938fb19cd2a3f0c212
