### ISSUE TITLE
Keep commercial resources but mark them as such.

### ISSUE THREAD

**Issue by matthewconstantine** [enaqx/awesome-react#386]
I saw the [recent commit](51edbfbd1d2b192f2b1b4b8d20a123455824e005) that removed some interesting, yet commercial resources. It would be wonderful if this list included non-free resources but simply marked as such. Or, maybe included in a separate section.

I'm not associated with any commercial projects or books. But I would happily trade dollars for the time savings of a well developed resource.

Thanks for maintaining this list. It's a wonderful resource!

**Comment by browniefed** [comment]
Yes, I was unaware that they were not allowed (hence me merging them). I'll look into bringing them back but maybe mark them with something? Put them in a category like `Paid Resources`?

Not sure what the path forward is here.

**Comment by enaqx** [comment]
This is opinion list and it should be made from personal experience of awesomeness. Most of the time i just can't verify quality of paid resources. It's kinda of out of square to put here resources based on titles only. Actually this list should be cleaned from outdated and irrelevant stuff and maintain only most valuable resources regarding React ecosystem available. Thanks for understanding.
