### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by Wildhoney** [enaqx/awesome-react#431]
We have PRs dating back to Oct 1 2015 &mdash; is this maintained any more?

**Comment by SPSpwetter** [comment]
Yes it is, most recent _closed_ pull request was March 11.

**Comment by Wildhoney** [comment]
[He closed that himself](https://github.com/enaqx/awesome-react/pull/417) before it was merged.

Last _merge_ was [https://github.com/enaqx/awesome-react/pull/389](62 days ago).

**Comment by brillout** [comment]
@enqx do you still maintain this? Most of the PRs I've seen are actually quite good

**Comment by enaqx** [comment]
Yes, it is maintained. We have another maintainer. I'll review new PRs ASAP.

**Comment by browniefed** [comment]
Apologies, got a bit busy and forgot to keep reviewing PRs.

**Comment by browniefed** [comment]
Handled as many as I could, now too many merge conflicts, so current PRs will need to be rebased.
