### ISSUE TITLE
Awesome React Components List

### ISSUE THREAD

**Issue by brillout** [enaqx/awesome-react#485]
Hi,
I'm creating this ticket as a follow up of https://github.com/sindresorhus/awesome/pull/698.
Are you still interested in collaborating?

**Comment by browniefed** [comment]
Yeah that'd be great, @enaqx you think you could give @brillout permissions to maintain  as well. Going to handle the react components section.

**Comment by enaqx** [comment]
Done. Pls, do not add every component in the world. This list is already quite overwhelming.

**Comment by brillout** [comment]
Yes it makes sense and I will try to maintain a high quality bar. Actually, I would remove some components from the current list that I regard as "not good enough". (I will do a PR and not push directly to get the approval of @browniefed and/or @enaqx)

That said many good components are missing and I think that we should add them.
The categorization should make the list feel less overwhelming.

As for the merge of the two lists mentioned in sindresorhus/awesome#698, I will hopefully find time this week to do it.
