### ISSUE TITLE
Merge `Awesome React Components` into `Awesome React`

### ISSUE THREAD

**Issue by brillout** [enaqx/awesome-react#503]
We want to merge https://github.com/brillout/awesome-react-components and https://github.com/enaqx/awesome-react. As mentioned in https://github.com/sindresorhus/awesome/pull/698.

I've reviewed all react libraries of the `Component` section of the `Awesome React` list.

https://gist.github.com/brillout/5fa9218b21f4a02067beb41c3ca212f8

50 % will be removed
30 % are already added to `Awesome React Components`
20 % are going to be added

My review is subjective and anyone is free to object.

@browniefed @enaqx
I've built a Frontend (http://devarchy.com/react-components) that allows anyone to review/vote whether or not a new entry should be added to the list.
No clue if people would actually do the effort of reviewing/voting but maybe it's worth a try? What do you think?

**Comment by stunaz** [comment]
So, what's up with this?

**Comment by brillout** [comment]
At this point I'd rather move all components from `awesome-react` to `awesome-react-components` and reference both lists to each other.
Having one big list feels clunky.

@stunaz 
@maullerz
@prijindal
@kirillDanshin

would you prefer two separated lists or one merged list?

**Comment by maullerz** [comment]
@brillout
Agree with that, i think **react-components** now really need their own separate awesome-list, and there we can group and order them independently

**Comment by kirillDanshin** [comment]
@brillout I prefer two separated lists.

**Comment by stunaz** [comment]
I am with @kirillDanshin , the list will be way too long. I prefer a dedicated one about only the comonents

**Comment by brillout** [comment]
👍 

As soon and if @browniefed @enaqx give their approval I will
 * review all components listed here and move them to `awesome-react-components`
 * same for all PRs adding a component
 * reference the two lists to each other

**Comment by browniefed** [comment]
I say go for it, I don't think anyone will mind

**Comment by enaqx** [comment]
I have cleaned components list and have included link to https://github.com/brillout/awesome-react-components. 

My suggestion is to add to this list only awesome awesome awesome components and stick to @brillout for more general-purpose components list.
