### ISSUE TITLE
Add another maintainer?

### ISSUE THREAD

**Issue by jashmenn** [enaqx/awesome-react#565]
Should we add another maintainer to this project? There's quite a lot of (aging) pull requests and some of them have great info. 

I volunteer to be a maintainer. 

One of the things I'd like to do is:

* have guidelines as to what is appropriate for inclusion so that folks know what to submit
* give feedback to every open pull request by either a) merging or b) describing why the request wasn't accepted
* potentially give some sort of ranking / popularity measure to e.g. components to help filter some of the noise

**Comment by browniefed** [comment]
I do not have that power, @enaqx

**Comment by dunnock** [comment]
I m volunteering too, can dedicate few hours a week.

**Comment by jashmenn** [comment]
Okay @browniefed, in https://github.com/enaqx/awesome-react/pull/533 I've merged ~14 outstanding pull requests. I vetted the links in each one individually and they're all high enough quality to be included here. There are also some real gems.

There's no conflicts and the tests pass.

### Details:
I've merged in:

* https://github.com/enaqx/awesome-react/pull/509
* https://github.com/enaqx/awesome-react/pull/516
* https://github.com/enaqx/awesome-react/pull/525
* https://github.com/enaqx/awesome-react/pull/527
* https://github.com/enaqx/awesome-react/pull/539
* https://github.com/enaqx/awesome-react/pull/540
* https://github.com/enaqx/awesome-react/pull/542
* https://github.com/enaqx/awesome-react/pull/544
* https://github.com/enaqx/awesome-react/pull/555
* https://github.com/enaqx/awesome-react/pull/558
* https://github.com/enaqx/awesome-react/pull/559
* https://github.com/enaqx/awesome-react/pull/560
* https://github.com/enaqx/awesome-react/pull/561
* https://github.com/enaqx/awesome-react/pull/563

**Comment by browniefed** [comment]
Wow awesome @jashmenn thank you.

**Comment by gkhno** [comment]
Is this project still maintained? I could not see any updates recently.

**Comment by brillout** [comment]
@browniefed @jashmenn

How about creating a fork? We would then be able to add maintainers.

We could create an organisation, create the awesome-react fork there, and also move awesome-react-components there.

**Comment by enaqx** [comment]
I can add other guys as collaborators. Please update here anyone who wants to volunteer.

**Comment by paulmelnikow** [comment]
I'd be happy to help. Seconded @jashmenn's suggestions in the top comment!

**Comment by Haroenv** [comment]
I'd like to volunteer to get the outstanding PRs merged @enaqx

**Comment by enaqx** [comment]
@paulmelnikow @Haroenv I've added you as collaborators. Thanks.

**Comment by paulmelnikow** [comment]
I'm glad to get the ball rolling!
