### ISSUE TITLE
adding more to boilerplates

### ISSUE THREAD

**Issue by shrynx** [enaqx/awesome-react#573]
@jashmenn How about adding react scripts forks, like [custom-react-scripts](https://www.npmjs.com/package/custom-react-scripts) (by @kitze) , [react-super-scripts](https://www.npmjs.com/package/react-super-scripts) (shameless self publicity 😉 ), ... etc.
I can make a quick pull request if you like .

**Comment by jashmenn** [comment]
Definitely create a pull request! That said, I don't have commit rights to this repo, though I'll probably create another aggregate pull req in January
