### ISSUE TITLE
CI is dead. It sad

### ISSUE THREAD

**Issue by kvolkovich-sc** [enaqx/awesome-react#621]
Something wrong with your travis. Can you fix it please?)

**Comment by vaidsu** [comment]
Its the same link that is complaining on all runs.

```
Issues :-(
> Links 
  1. [L0649]  https://rnplay.org/ SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 
  2. [L0726] 404 http://jamesfriend.com.au/implementing-flux-coffeescript  
> Dupes 
  None ✓
```

It may be easier to just remove or change those links to solve, but I am not the owner of those links. So waiting!

**Comment by vaidsu** [comment]
I have this https://github.com/enaqx/awesome-react/pull/622 lets see if it gets accepted.

**Comment by kvolkovich-sc** [comment]
It can not last forever. We need the power of @enaqx  :smiley:

**Comment by vaidsu** [comment]
@kvolkovich-sc If you look at this: https://travis-ci.org/enaqx/awesome-react/builds/219013697 it seems like something from the Travis end is wrong. I tried locally - it worked.
