### ISSUE TITLE
Require that PRs include the links in the description

### ISSUE THREAD

**Issue by wmertens** [enaqx/awesome-react#625]
…that way, maintainers and people following along with the changes can look at the proposed content with way fewer clicks.

**Comment by paulmelnikow** [comment]
That's a nice idea. Are there any awesome-list-PR-bots which can help with this?

**Comment by Haroenv** [comment]
danger could be used for this too

**Comment by paulmelnikow** [comment]
Let's do that!

We'll need at least admin access to set that up. @enaqx would you mind granting us that?

**Comment by enaqx** [comment]
@paulmelnikow 
I'll set up danger to require this.

**Comment by paulmelnikow** [comment]
@enaqx Would you mind granting admin access so we could set this up?

**Comment by paulmelnikow** [comment]
Or is it something you'd still like to set up? I've started using Danger for Shields, it works nice.
