### ISSUE TITLE
Add Meetups around the globe

### ISSUE THREAD

**Issue by alejandronanez** [enaqx/awesome-react#634]
It would be helpful to have a list like the one we have in here: [React Wiki](https://github.com/facebook/react/wiki/Meetups)

I can make a PR if you're ok with this.

Thanks!

**Comment by paulmelnikow** [comment]
How about a link to that list under Community?

**Comment by alejandronanez** [comment]
Hmmm that could work too. I think having explicitly all meetups here would be easier, wiki pages tend to outdate quite easily.

I don't have strong opinions about this though, let me know how can I help.

Thanks!

**Comment by Haroenv** [comment]
Let's start with the easy thing, feel free to open a PR @alejandronanez

**Comment by alejandronanez** [comment]
Cool, will do.

Thanks!
