### ISSUE TITLE
Remove - Learn React by building the Hacker News front page

### ISSUE THREAD

**Issue by ucg8j** [enaqx/awesome-react#752]
I've just tried using [the tutorial](https://github.com/mking/react-hn). Unfortunately, the repo has not been maintained (no recent commits + stale PRs) and is no longer a good intro for beginners. A bunch of issues are experienced from the outset due to the syntax not being up-to-date with the most recent release of React.

I would suggest this tutorial is no longer 'awesome'. @enaqx are you ok with me submitting a PR to remove it?

**Comment by paulmelnikow** [comment]
Hi! Yes, please do open a PR. Thanks.

**Comment by ucg8j** [comment]
Fixed with [PR #753](https://github.com/enaqx/awesome-react/pull/753)
