### ISSUE TITLE
Links of the Server-Client with React section doesn't work in the readme file

### ISSUE THREAD

**Issue by seb9465** [enaqx/awesome-react#810]
When clicking on the links of that section, I end up on an error page in the readme file.

**Comment by Haroenv** [comment]
https://github.com/enaqx/awesome-react#server-client-with-react seems to go to the right section for me 🤔

**Comment by seb9465** [comment]
The problem is when you click on the links below, the one that should get you to the tutorials. Sorry for that misunderstanding.
