### ISSUE TITLE
add hooks section

### ISSUE THREAD

**Issue by venil7** [enaqx/awesome-react#887]
and then merge with [awesome react hooks](https://github.com/rehooks/awesome-react-hooks)

**Comment by Haroenv** [comment]
PR welcome

**Comment by xianrusso** [comment]
YES!

**Comment by enaqx** [comment]
https://github.com/enaqx/awesome-react/commit/c0477f2b431aee13041633dbd823d0e5bf07dfb2

Thanks for the suggestion!
