### ISSUE TITLE
Consider separating toolkits from boilerplates

### ISSUE THREAD

**Issue by eparizzi** [enaqx/awesome-react#895]
Right now we have things like create-react-app and next.js along with just-another-react-boilerplate. Which aren't the same thing. The former are considered "toolkits" or "frameworks" while the later is just a plain boilerplate.

So things that allows you to create a project and leverage their packages to run, test and build the project without worrying about the underlying packages would fit better in its own category.

A few examples of these:
create-react-app
nwb
next.js
neutrino
razzle
rekit

**Comment by Haroenv** [comment]
Would you be willing to make a PR fixing this discrepancy?

**Comment by eparizzi** [comment]
There you go! 
https://github.com/enaqx/awesome-react/pull/896

**Comment by Haroenv** [comment]
good start, thanks!
