### ISSUE TITLE
add: react JSX filter

### ISSUE THREAD

**Issue by chiaweilee** [enaqx/awesome-react#914]
# [react-jsx-filter](https://github.com/chiaweilee/react-jsx-filter)
*JSX filter support for React*, base on [babel-plugin-transform-react-jsx-filter](https://github.com/chiaweilee/react-jsx-filter/tree/master/packages/babel-plugin-transform-react-jsx-filter)

### Example

```react.js
// <div>React</div>
<div>{ 'react' | capitalize }</div>
```

```react.js
// <div>3</div>
<div>{ 1 | addOne | addOne | addOne }</div>
```

```react.js
// <div>你好</div>
<div>{ 'hello' | translate('zh-cn') }</div>
```

```react.js
// with lodash
<div>{ this.state.data | _.filter({ 'active': true }) | this.renderTable }</div>
```

**Comment by Haroenv** [comment]
You can add this to the "template engines" heading, I think it fits best there
